name: Docker Build and Push

on:
  push:
    branches:
      - main # Or your main branch
    paths:
      - 'rust-compressor/**'  # Trigger only for changes in these paths
      - 'js-compressor/**'    # Trigger only for changes in these paths
      - '.github/workflows/docker.yml' # Trigger if this file changes
  pull_request:
    branches:
      - main # Or your main branch
    paths:
      - 'rust-compressor/**'
      - 'js-compressor/**'
      - '.github/workflows/docker.yml'

jobs:
  build-and-push:
    # Use a matrix strategy to define different images to build
    strategy:
      matrix:
        image:
          - rust-compressor
          - js-compressor
        path: # Added 'path' here to be more explicit
          - 'rust-compressor'
          - 'js-compressor'
    name: Build and push ${{ matrix.image }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Grant push permission to the GITHUB_TOKEN
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # IMPORTANT: Use sparse-checkout to only fetch the necessary paths.
        with:
          sparse-checkout: |
            .github/workflows/docker.yml
            ${{ matrix.path }} # Use matrix.path

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.path }}  # Use matrix.path here
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:${{ github.sha }}
